#############################################################################
# Makefile for building: asu
# Generated by qmake (1.07a) (Qt 3.3.8b) on: Wed Jul 22 17:29:57 2020
# Project:  asu.pro
# Template: app
# Command: $(QMAKE) -o Makefile asu.pro
#############################################################################

####### Compiler, tools and options

CC       = gcc
CXX      = g++
LEX      = flex
YACC     = yacc
CFLAGS   = -pipe -g -Wall -W -O0 -D_REENTRANT  -DUSE_UNIT_TEST -DASTRA -DLinux -DQT_THREAD_SUPPORT -DQT_SHARED -DQT_TABLET_SUPPORT -DQT_NO_DEBUG
CXXFLAGS = -pipe -g -Wall -W -O0 -fpermissive -D_REENTRANT  -DUSE_UNIT_TEST -DASTRA -DLinux -DQT_THREAD_SUPPORT -DQT_SHARED -DQT_TABLET_SUPPORT -DQT_NO_DEBUG
LEXFLAGS = 
YACCFLAGS= -d
INCPATH  = -I/usr/share/qt3/mkspecs/default -I. -I../UnitTest/src -I../base/Common -I../base/Connect -I../base/FA -I../base/GUI -I../base/Systems -I../base/VSI -I../base -I../middle/Connect -I../middle/Headers -I../middle/xml -I../middle -IConnect -IFA -IGUI -I/usr/include/qt3 -I.ui/ -I.moc/
LINK     = g++
LFLAGS   = -fpermissive
LIBS     = $(SUBLIBS) -L/usr/share/qt3/lib -L/usr/X11R6/lib -lXUnitTest -L/usr/local/lib -lqt-mt -lXext -lX11 -lm -lpthread
AR       = ar cqs
RANLIB   = 
MOC      = /usr/share/qt3/bin/moc
UIC      = /usr/share/qt3/bin/uic
QMAKE    = qmake
TAR      = tar -cf
GZIP     = gzip -9f
COPY     = cp -f
COPY_FILE= $(COPY)
COPY_DIR = $(COPY) -r
INSTALL_FILE= $(COPY_FILE)
INSTALL_DIR = $(COPY_DIR)
DEL_FILE = rm -f
SYMLINK  = ln -sf
DEL_DIR  = rmdir
MOVE     = mv -f
CHK_DIR_EXISTS= test -d
MKDIR    = mkdir -p

####### Output directory

OBJECTS_DIR = .obj/

####### Files

HEADERS = ../base/Common/BaseTypes.h \
		../base/Common/AltChuLib.h \
		../base/Connect/BaseConnect.h \
		../base/Connect/BaseOperate.h \
		../base/Connect/connect.h \
		../base/Connect/conthread.h \
		../base/Connect/manchconnect.h \
		../base/Connect/OperateThread.h \
		../base/FA/basepim.h \
		../base/FA/pimth.h \
		../base/GUI/BazeIndicator.h \
		../base/GUI/BitKart.h \
		../base/GUI/CircularIndicator.h \
		../base/GUI/DecartIndicator.h \
		../base/GUI/factoryindicator.h \
		../base/GUI/formth.h \
		../base/GUI/GeneralPixpam.h \
		../base/GUI/GeometricIndicator.h \
		../base/GUI/IndicatorWidget.h \
		../base/GUI/MenuIndicator.h \
		../base/GUI/ObjectPainter.h \
		../base/GUI/ObjectRect.h \
		../base/GUI/PolimentIndicator.h \
		../base/GUI/QtObjectPainter.h \
		../base/GUI/QtPixMap.h \
		../base/GUI/QtRgbColor.h \
		../base/GUI/RGBColor.h \
		../base/GUI/ScanIndicator.h \
		support.h \
		../base/GUI/TableIndicator.h \
		../base/GUI/unitablefactory.h \
		../base/GUI/unitablefactoryA.h \
		../base/GUI/unitableindicator.h \
		../base/GUI/unitableindicatorA.h \
		../base/Systems/timethread.h \
		../base/VSI/reader.h \
		../base/VSI/readerVSI.h \
		../middle/Connect/EthImTO.h \
		../middle/Connect/EthRecvRLS.h \
		../middle/Connect/EthRecvAKNG.h \
		../middle/Connect/EthRecvCEB.h \
		../middle/Connect/EthRecvKGMO.h \
		../middle/Headers/3P-99.h \
		../middle/Headers/3P-99_MTK.h \
		../middle/Headers/5n-10_upr.h \
		../middle/Headers/ASU_REP.h \
		../middle/Headers/ImTO.h \
		../middle/Headers/ot_AKNG.h \
		../middle/Headers/ot_SEV.h \
		../middle/Headers/RLK_ACY.h \
		../middle/Headers/st_palash.h \
		../middle/Headers/st_zak.h \
		../middle/Headers/st_zrk.h \
		../middle/Headers/MCE.h \
		../middle/enums.h \
		FA/pimasu.h \
		FA/rc.h \
		GUI/asuCircFactory.h \
		GUI/asuCircIndicator.h \
		GUI/asuCommandFactory.h \
		GUI/asuCommandIndicator.h \
		GUI/asuDecFactory.h \
		GUI/asuDecIndicator.h \
		GUI/asufactory.h \
		GUI/asuSetFactory.h \
		GUI/asuSetIndicator.h \
		GUI/asuShipFactory.h \
		GUI/asuShipIndicator.h \
		GUI/asuUTFactory.h \
		GUI/canvaswidget.h \
		Connect/asuOperate.h \
		asusettings.h \
		scheduler.h
SOURCES = ../base/Common/AltChuLib.cpp \
		../base/Connect/BaseConnect.cpp \
		../base/Connect/BaseOperate.cpp \
		../base/Connect/connect.cpp \
		../base/Connect/conthread.cpp \
		../base/Connect/OperateThread.cpp \
		../base/FA/pimth.cpp \
		../base/GUI/BazeIndicator.cpp \
		../base/GUI/BitKart.cpp \
		../base/GUI/CircularIndicator.cpp \
		../base/GUI/DecartIndicator.cpp \
		../base/GUI/Encoding.cpp \
		../base/GUI/factoryindicator.cpp \
		../base/GUI/formth.cpp \
		../base/GUI/GeneralPixpam.cpp \
		../base/GUI/GeometricIndicator.cpp \
		../base/GUI/IndicatorWidget.cpp \
		../base/GUI/MenuIndicator.cpp \
		../base/GUI/ObjectPainter.cpp \
		../base/GUI/ObjectRect.cpp \
		../base/GUI/QtObjectPainter.cpp \
		../base/GUI/QtPixMap.cpp \
		../base/GUI/QtRgbColor.cpp \
		../base/GUI/RGBColor.cpp \
		../base/GUI/TableIndicator.cpp \
		../base/GUI/unitablefactory.cpp \
		../base/GUI/unitablefactoryA.cpp \
		../base/GUI/unitableindicator.cpp \
		../base/GUI/unitableindicatorA.cpp \
		../base/Systems/timethread.cpp \
		../base/VSI/reader.cpp \
		../base/VSI/readerVSI.cpp \
		../middle/Connect/EthRecvAKNG.cpp \
		../middle/Connect/EthImTO.cpp \
		../middle/Connect/EthRecvRLS.cpp \
		../middle/Connect/EthRecvCEB.cpp \
		../middle/Connect/EthRecvKGMO.cpp \
		FA/pimasu.cpp \
		FA/rc.cpp \
		FA/eco.cpp \
		FA/ipackasu.cpp \
		FA/control.cpp \
		FA/modelasu.cpp \
		GUI/asuCircFactory.cpp \
		GUI/asuCircIndicator.cpp \
		GUI/asuCommandIndicator.cpp \
		GUI/asuCommandFactory.cpp \
		GUI/asuDecFactory.cpp \
		GUI/asuDecIndicator.cpp \
		GUI/asufactory.cpp \
		GUI/asuSetFactory.cpp \
		GUI/asuSetIndicator.cpp \
		GUI/asuShipFactory.cpp \
		GUI/asuShipIndicator.cpp \
		GUI/asuUTFactory.cpp \
		GUI/canvaswidget.cpp \
		Connect/asuOperate.cpp \
		main.cpp \
		scheduler.cpp
OBJECTS = .obj/AltChuLib.o \
		.obj/BaseConnect.o \
		.obj/BaseOperate.o \
		.obj/connect.o \
		.obj/conthread.o \
		.obj/OperateThread.o \
		.obj/pimth.o \
		.obj/BazeIndicator.o \
		.obj/BitKart.o \
		.obj/CircularIndicator.o \
		.obj/DecartIndicator.o \
		.obj/Encoding.o \
		.obj/factoryindicator.o \
		.obj/formth.o \
		.obj/GeneralPixpam.o \
		.obj/GeometricIndicator.o \
		.obj/IndicatorWidget.o \
		.obj/MenuIndicator.o \
		.obj/ObjectPainter.o \
		.obj/ObjectRect.o \
		.obj/QtObjectPainter.o \
		.obj/QtPixMap.o \
		.obj/QtRgbColor.o \
		.obj/RGBColor.o \
		.obj/TableIndicator.o \
		.obj/unitablefactory.o \
		.obj/unitablefactoryA.o \
		.obj/unitableindicator.o \
		.obj/unitableindicatorA.o \
		.obj/timethread.o \
		.obj/reader.o \
		.obj/readerVSI.o \
		.obj/EthRecvAKNG.o \
		.obj/EthImTO.o \
		.obj/EthRecvRLS.o \
		.obj/EthRecvCEB.o \
		.obj/EthRecvKGMO.o \
		.obj/pimasu.o \
		.obj/rc.o \
		.obj/eco.o \
		.obj/ipackasu.o \
		.obj/control.o \
		.obj/modelasu.o \
		.obj/asuCircFactory.o \
		.obj/asuCircIndicator.o \
		.obj/asuCommandIndicator.o \
		.obj/asuCommandFactory.o \
		.obj/asuDecFactory.o \
		.obj/asuDecIndicator.o \
		.obj/asufactory.o \
		.obj/asuSetFactory.o \
		.obj/asuSetIndicator.o \
		.obj/asuShipFactory.o \
		.obj/asuShipIndicator.o \
		.obj/asuUTFactory.o \
		.obj/canvaswidget.o \
		.obj/asuOperate.o \
		.obj/main.o \
		.obj/scheduler.o
FORMS = 
UICDECLS = 
UICIMPLS = 
SRCMOC   = 
OBJMOC = 
DIST	   = asu.pro
QMAKE_TARGET = asu
DESTDIR  = 
TARGET   = asu

first: all
####### Implicit rules

.SUFFIXES: .c .o .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(UICDECLS) $(OBJECTS) $(OBJMOC)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(OBJCOMP) $(LIBS)

mocables: $(SRCMOC)
uicables: $(UICDECLS) $(UICIMPLS)

$(MOC): 
	( cd $(QTDIR)/src/moc && $(MAKE) )

Makefile: asu.pro  /usr/share/qt3/mkspecs/default/qmake.conf /usr/share/qt3/lib/libqt-mt.prl
	$(QMAKE) -o Makefile asu.pro
qmake: 
	@$(QMAKE) -o Makefile asu.pro

dist: 
	@mkdir -p .obj/asu && $(COPY_FILE) --parents $(SOURCES) $(HEADERS) $(FORMS) $(DIST) .obj/asu/ && ( cd `dirname .obj/asu` && $(TAR) asu.tar asu && $(GZIP) asu.tar ) && $(MOVE) `dirname .obj/asu`/asu.tar.gz . && $(DEL_FILE) -r .obj/asu

mocclean:

uiclean:

yaccclean:
lexclean:
clean:
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) $(TARGET)


FORCE:

####### Compile

.obj/AltChuLib.o: ../base/Common/AltChuLib.cpp ../base/Common/AltChuLib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/AltChuLib.o ../base/Common/AltChuLib.cpp

.obj/BaseConnect.o: ../base/Connect/BaseConnect.cpp ../base/Connect/BaseConnect.h \
		../base/Connect/conthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/BaseConnect.o ../base/Connect/BaseConnect.cpp

.obj/BaseOperate.o: ../base/Connect/BaseOperate.cpp ../base/Connect/BaseOperate.h \
		../base/Connect/connect.h \
		../base/Connect/BaseConnect.h \
		../base/Connect/conthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/BaseOperate.o ../base/Connect/BaseOperate.cpp

.obj/connect.o: ../base/Connect/connect.cpp ../base/Connect/connect.h \
		../base/Connect/conthread.h \
		../base/Connect/BaseConnect.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/connect.o ../base/Connect/connect.cpp

.obj/conthread.o: ../base/Connect/conthread.cpp ../base/Connect/conthread.h \
		../base/Connect/connect.h \
		../base/Connect/BaseConnect.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/conthread.o ../base/Connect/conthread.cpp

.obj/OperateThread.o: ../base/Connect/OperateThread.cpp ../base/Connect/OperateThread.h \
		../base/Connect/conthread.h \
		../base/Connect/connect.h \
		../base/Connect/BaseOperate.h \
		../base/Connect/BaseConnect.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/OperateThread.o ../base/Connect/OperateThread.cpp

.obj/pimth.o: ../base/FA/pimth.cpp ../base/FA/pimth.h \
		../base/FA/basepim.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/pimth.o ../base/FA/pimth.cpp

.obj/BazeIndicator.o: ../base/GUI/BazeIndicator.cpp support.h \
		../base/GUI/QtPixMap.h \
		../base/GUI/QtObjectPainter.h \
		../base/GUI/BazeIndicator.h \
		asusettings.h \
		../base/GUI/GeneralPixpam.h \
		../base/GUI/RGBColor.h \
		../base/GUI/ObjectPainter.h \
		../base/GUI/BitKart.h \
		../base/GUI/IndicatorWidget.h \
		../base/GUI/ObjectRect.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/BazeIndicator.o ../base/GUI/BazeIndicator.cpp

.obj/BitKart.o: ../base/GUI/BitKart.cpp ../base/GUI/BitKart.h \
		support.h \
		asusettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/BitKart.o ../base/GUI/BitKart.cpp

.obj/CircularIndicator.o: ../base/GUI/CircularIndicator.cpp support.h \
		../base/GUI/QtObjectPainter.h \
		../base/GUI/CircularIndicator.h \
		asusettings.h \
		../base/GUI/RGBColor.h \
		../base/GUI/ObjectPainter.h \
		../base/GUI/QtPixMap.h \
		../base/GUI/GeneralPixpam.h \
		../base/GUI/GeometricIndicator.h \
		../base/GUI/BazeIndicator.h \
		../base/GUI/BitKart.h \
		../base/GUI/IndicatorWidget.h \
		../base/GUI/ObjectRect.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/CircularIndicator.o ../base/GUI/CircularIndicator.cpp

.obj/DecartIndicator.o: ../base/GUI/DecartIndicator.cpp support.h \
		../base/GUI/QtObjectPainter.h \
		../base/GUI/DecartIndicator.h \
		asusettings.h \
		../base/GUI/RGBColor.h \
		../base/GUI/ObjectPainter.h \
		../base/GUI/QtPixMap.h \
		../base/GUI/GeneralPixpam.h \
		../base/GUI/GeometricIndicator.h \
		../base/GUI/BazeIndicator.h \
		../base/GUI/BitKart.h \
		../base/GUI/IndicatorWidget.h \
		../base/GUI/ObjectRect.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/DecartIndicator.o ../base/GUI/DecartIndicator.cpp

.obj/Encoding.o: ../base/GUI/Encoding.cpp ../base/GUI/Encoding.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/Encoding.o ../base/GUI/Encoding.cpp

.obj/factoryindicator.o: ../base/GUI/factoryindicator.cpp ../base/GUI/factoryindicator.h \
		support.h \
		../base/GUI/QtPixMap.h \
		../base/GUI/QtObjectPainter.h \
		../base/GUI/BazeIndicator.h \
		asusettings.h \
		../base/GUI/RGBColor.h \
		../base/GUI/GeneralPixpam.h \
		../base/GUI/BitKart.h \
		../base/GUI/IndicatorWidget.h \
		../base/GUI/ObjectRect.h \
		../base/GUI/ObjectPainter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/factoryindicator.o ../base/GUI/factoryindicator.cpp

.obj/formth.o: ../base/GUI/formth.cpp ../base/GUI/formth.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/formth.o ../base/GUI/formth.cpp

.obj/GeneralPixpam.o: ../base/GUI/GeneralPixpam.cpp ../base/GUI/GeneralPixpam.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/GeneralPixpam.o ../base/GUI/GeneralPixpam.cpp

.obj/GeometricIndicator.o: ../base/GUI/GeometricIndicator.cpp support.h \
		../base/GUI/GeometricIndicator.h \
		asusettings.h \
		../base/GUI/BazeIndicator.h \
		../base/GUI/ObjectPainter.h \
		../base/GUI/RGBColor.h \
		../base/GUI/GeneralPixpam.h \
		../base/GUI/BitKart.h \
		../base/GUI/IndicatorWidget.h \
		../base/GUI/ObjectRect.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/GeometricIndicator.o ../base/GUI/GeometricIndicator.cpp

.obj/IndicatorWidget.o: ../base/GUI/IndicatorWidget.cpp support.h \
		../base/GUI/IndicatorWidget.h \
		asusettings.h \
		../base/GUI/RGBColor.h \
		../base/GUI/ObjectRect.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/IndicatorWidget.o ../base/GUI/IndicatorWidget.cpp

.obj/MenuIndicator.o: ../base/GUI/MenuIndicator.cpp support.h \
		../base/GUI/QtObjectPainter.h \
		../base/GUI/MenuIndicator.h \
		asusettings.h \
		../base/GUI/RGBColor.h \
		../base/GUI/ObjectPainter.h \
		../base/GUI/QtPixMap.h \
		../base/GUI/GeneralPixpam.h \
		../base/GUI/BazeIndicator.h \
		../base/GUI/BitKart.h \
		../base/GUI/IndicatorWidget.h \
		../base/GUI/ObjectRect.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/MenuIndicator.o ../base/GUI/MenuIndicator.cpp

.obj/ObjectPainter.o: ../base/GUI/ObjectPainter.cpp ../base/GUI/ObjectPainter.h \
		support.h \
		../base/GUI/GeneralPixpam.h \
		../base/GUI/RGBColor.h \
		asusettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/ObjectPainter.o ../base/GUI/ObjectPainter.cpp

.obj/ObjectRect.o: ../base/GUI/ObjectRect.cpp ../base/GUI/ObjectRect.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/ObjectRect.o ../base/GUI/ObjectRect.cpp

.obj/QtObjectPainter.o: ../base/GUI/QtObjectPainter.cpp ../base/GUI/QtRgbColor.h \
		../base/GUI/QtObjectPainter.h \
		../base/GUI/RGBColor.h \
		../base/GUI/ObjectPainter.h \
		../base/GUI/QtPixMap.h \
		support.h \
		../base/GUI/GeneralPixpam.h \
		asusettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/QtObjectPainter.o ../base/GUI/QtObjectPainter.cpp

.obj/QtPixMap.o: ../base/GUI/QtPixMap.cpp ../base/GUI/QtPixMap.h \
		../base/GUI/GeneralPixpam.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/QtPixMap.o ../base/GUI/QtPixMap.cpp

.obj/QtRgbColor.o: ../base/GUI/QtRgbColor.cpp ../base/GUI/QtRgbColor.h \
		../base/GUI/RGBColor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/QtRgbColor.o ../base/GUI/QtRgbColor.cpp

.obj/RGBColor.o: ../base/GUI/RGBColor.cpp ../base/GUI/RGBColor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/RGBColor.o ../base/GUI/RGBColor.cpp

.obj/TableIndicator.o: ../base/GUI/TableIndicator.cpp support.h \
		../base/GUI/QtObjectPainter.h \
		../base/GUI/TableIndicator.h \
		asusettings.h \
		../base/GUI/RGBColor.h \
		../base/GUI/ObjectPainter.h \
		../base/GUI/QtPixMap.h \
		../base/GUI/GeneralPixpam.h \
		../base/GUI/GeometricIndicator.h \
		../base/GUI/IndicatorWidget.h \
		../base/GUI/BazeIndicator.h \
		../base/GUI/BitKart.h \
		../base/GUI/ObjectRect.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/TableIndicator.o ../base/GUI/TableIndicator.cpp

.obj/unitablefactory.o: ../base/GUI/unitablefactory.cpp ../base/GUI/unitablefactory.h \
		../base/GUI/unitableindicator.h \
		../base/GUI/unitablefactoryA.h \
		../base/GUI/BitKart.h \
		../base/GUI/QtPixMap.h \
		../base/GUI/factoryindicator.h \
		support.h \
		../base/GUI/BazeIndicator.h \
		asusettings.h \
		../base/GUI/RGBColor.h \
		../base/GUI/GeneralPixpam.h \
		../base/GUI/IndicatorWidget.h \
		../base/GUI/ObjectRect.h \
		../base/GUI/MenuIndicator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/unitablefactory.o ../base/GUI/unitablefactory.cpp

.obj/unitablefactoryA.o: ../base/GUI/unitablefactoryA.cpp ../base/GUI/unitablefactoryA.h \
		../base/GUI/unitableindicatorA.h \
		../base/GUI/BitKart.h \
		../base/GUI/QtPixMap.h \
		../base/GUI/QtObjectPainter.h \
		../base/GUI/factoryindicator.h \
		support.h \
		../base/GUI/BazeIndicator.h \
		asusettings.h \
		../base/GUI/RGBColor.h \
		../base/GUI/GeneralPixpam.h \
		../base/GUI/IndicatorWidget.h \
		../base/GUI/ObjectRect.h \
		../base/GUI/MenuIndicator.h \
		../base/GUI/TableIndicator.h \
		../base/GUI/ObjectPainter.h \
		../base/GUI/GeometricIndicator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/unitablefactoryA.o ../base/GUI/unitablefactoryA.cpp

.obj/unitableindicator.o: ../base/GUI/unitableindicator.cpp ../base/GUI/unitableindicator.h \
		../base/GUI/MenuIndicator.h \
		../base/GUI/BazeIndicator.h \
		support.h \
		../base/GUI/RGBColor.h \
		../base/GUI/GeneralPixpam.h \
		../base/GUI/BitKart.h \
		../base/GUI/IndicatorWidget.h \
		asusettings.h \
		../base/GUI/ObjectRect.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/unitableindicator.o ../base/GUI/unitableindicator.cpp

.obj/unitableindicatorA.o: ../base/GUI/unitableindicatorA.cpp ../base/GUI/unitableindicatorA.h \
		../base/GUI/BitKart.h \
		../base/GUI/QtPixMap.h \
		../base/GUI/QtObjectPainter.h \
		../base/GUI/MenuIndicator.h \
		../base/GUI/TableIndicator.h \
		../base/GUI/ObjectPainter.h \
		../base/GUI/BazeIndicator.h \
		support.h \
		../base/GUI/RGBColor.h \
		../base/GUI/GeneralPixpam.h \
		../base/GUI/IndicatorWidget.h \
		asusettings.h \
		../base/GUI/ObjectRect.h \
		../base/GUI/GeometricIndicator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/unitableindicatorA.o ../base/GUI/unitableindicatorA.cpp

.obj/timethread.o: ../base/Systems/timethread.cpp ../base/Systems/timethread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/timethread.o ../base/Systems/timethread.cpp

.obj/reader.o: ../base/VSI/reader.cpp ../base/VSI/reader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/reader.o ../base/VSI/reader.cpp

.obj/readerVSI.o: ../base/VSI/readerVSI.cpp ../base/VSI/readerVSI.h \
		../base/VSI/reader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/readerVSI.o ../base/VSI/readerVSI.cpp

.obj/EthRecvAKNG.o: ../middle/Connect/EthRecvAKNG.cpp ../middle/Connect/EthRecvAKNG.h \
		support.h \
		asusettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/EthRecvAKNG.o ../middle/Connect/EthRecvAKNG.cpp

.obj/EthImTO.o: ../middle/Connect/EthImTO.cpp ../middle/Connect/EthImTO.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/EthImTO.o ../middle/Connect/EthImTO.cpp

.obj/EthRecvRLS.o: ../middle/Connect/EthRecvRLS.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/EthRecvRLS.o ../middle/Connect/EthRecvRLS.cpp

.obj/EthRecvCEB.o: ../middle/Connect/EthRecvCEB.cpp ../middle/Connect/EthRecvCEB.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/EthRecvCEB.o ../middle/Connect/EthRecvCEB.cpp

.obj/EthRecvKGMO.o: ../middle/Connect/EthRecvKGMO.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/EthRecvKGMO.o ../middle/Connect/EthRecvKGMO.cpp

.obj/pimasu.o: FA/pimasu.cpp FA/pimasu.h \
		FA/rc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/pimasu.o FA/pimasu.cpp

.obj/rc.o: FA/rc.cpp FA/pimasu.h \
		FA/rc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/rc.o FA/rc.cpp

.obj/eco.o: FA/eco.cpp FA/pimasu.h \
		FA/rc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/eco.o FA/eco.cpp

.obj/ipackasu.o: FA/ipackasu.cpp FA/pimnpu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/ipackasu.o FA/ipackasu.cpp

.obj/control.o: FA/control.cpp FA/pimasu.h \
		FA/rc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/control.o FA/control.cpp

.obj/modelasu.o: FA/modelasu.cpp FA/pimasu.h \
		FA/rc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/modelasu.o FA/modelasu.cpp

.obj/asuCircFactory.o: GUI/asuCircFactory.cpp GUI/asuCircFactory.h \
		GUI/asuCircIndicator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/asuCircFactory.o GUI/asuCircFactory.cpp

.obj/asuCircIndicator.o: GUI/asuCircIndicator.cpp GUI/asuCircIndicator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/asuCircIndicator.o GUI/asuCircIndicator.cpp

.obj/asuCommandIndicator.o: GUI/asuCommandIndicator.cpp GUI/asuCommandIndicator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/asuCommandIndicator.o GUI/asuCommandIndicator.cpp

.obj/asuCommandFactory.o: GUI/asuCommandFactory.cpp GUI/asuCommandFactory.h \
		GUI/asuCommandIndicator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/asuCommandFactory.o GUI/asuCommandFactory.cpp

.obj/asuDecFactory.o: GUI/asuDecFactory.cpp GUI/asuDecFactory.h \
		GUI/asuDecIndicator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/asuDecFactory.o GUI/asuDecFactory.cpp

.obj/asuDecIndicator.o: GUI/asuDecIndicator.cpp GUI/asuDecIndicator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/asuDecIndicator.o GUI/asuDecIndicator.cpp

.obj/asufactory.o: GUI/asufactory.cpp GUI/asufactory.h \
		GUI/asuShipFactory.h \
		GUI/asuDecFactory.h \
		GUI/asuCircFactory.h \
		GUI/asuFlightTaskFactory.h \
		GUI/asuCommandFactory.h \
		GUI/asuSetFactory.h \
		GUI/asuUTFactory.h \
		GUI/asuShipIndicator.h \
		GUI/asuDecIndicator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/asufactory.o GUI/asufactory.cpp

.obj/asuSetFactory.o: GUI/asuSetFactory.cpp GUI/asuSetFactory.h \
		GUI/asuSetIndicator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/asuSetFactory.o GUI/asuSetFactory.cpp

.obj/asuSetIndicator.o: GUI/asuSetIndicator.cpp GUI/asuSetIndicator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/asuSetIndicator.o GUI/asuSetIndicator.cpp

.obj/asuShipFactory.o: GUI/asuShipFactory.cpp GUI/asuShipFactory.h \
		GUI/asuShipIndicator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/asuShipFactory.o GUI/asuShipFactory.cpp

.obj/asuShipIndicator.o: GUI/asuShipIndicator.cpp GUI/asuShipIndicator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/asuShipIndicator.o GUI/asuShipIndicator.cpp

.obj/asuUTFactory.o: GUI/asuUTFactory.cpp GUI/asuUTFactory.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/asuUTFactory.o GUI/asuUTFactory.cpp

.obj/canvaswidget.o: GUI/canvaswidget.cpp asusettings.h \
		GUI/canvaswidget.h \
		GUI/npufactory.h \
		support.h \
		GUI/npuMenuIndicator.h \
		GUI/npuMainIndicator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/canvaswidget.o GUI/canvaswidget.cpp

.obj/asuOperate.o: Connect/asuOperate.cpp Connect/asuOperate.h \
		asusettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/asuOperate.o Connect/asuOperate.cpp

.obj/main.o: main.cpp scheduler.h \
		support.h \
		asusettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/main.o main.cpp

.obj/scheduler.o: scheduler.cpp scheduler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/scheduler.o scheduler.cpp

####### Install

install:  

uninstall:  

